export const idTemplate = {
  diseases: [
    {id:"JlvnlXM", item:"鉄欠乏性貧血"},
    {id:"JlvnlYM", item:"ビタミンB12欠乏性貧血"},
    {id:"JlvnlZE", item:"播種性血管内凝固<DIC>"},
    {id:"JlvnlcA", item:"脳出血"},
    {id:"JlvnlcE", item:"くも膜下出血"},
    {id:"JlvnlcQ", item:"脳梗塞"},
    {id:"JlvnlcY", item:"一過性脳虚血発作"},
    {id:"Jlvnlcw", item:"脳炎・髄膜炎"},
    {id:"JlvnldE", item:"多発性硬化症"},
    {id:"JlvnldM", item:"Alzheimer型認知症"},
    {id:"Jlvnldc", item:"Parkinson病"},
    {id:"JlvnleU", item:"重症筋無力症"},
    {id:"Jlvnleo", item:"全般てんかん"},
    {id:"Jlvnles", item:"局在関連てんかん"},
    {id:"Jlvnle0", item:"片頭痛"},
    {id:"Jlvnle8", item:"緊張型頭痛"},
    {id:"JlvnlfU", item:"急性硬膜外血腫"},
    {id:"JlvnlfY", item:"硬膜下血腫（急性・慢性）"},
    {id:"JlvnlgE", item:"湿疹反応（湿疹三角）"},
    {id:"JlvnlgM", item:"接触皮膚炎"},
    {id:"JlvnlgQ", item:"アトピー性皮膚炎"},
    {id:"Jlvnlg4", item:"蕁麻疹"},
    {id:"Jlvnlh8", item:"Stevens-Johnson症候群"},
    {id:"Jlvnljk", item:"蜂窩織炎"},
    {id:"Jlvnlj8", item:"疥癬"},
    {id:"Jlvnlk8", item:"後天性免疫不全症候群<AIDS>に伴う皮膚症状（梅毒・難治性ヘルペス・伝染性軟属腫・Kaposi肉腫等）"},
    {id:"JlvnlkE", item:"単純ヘルペス"},
    {id:"JlvnlkM", item:"帯状疱疹"},
    {id:"Jlvnlkc", item:"麻疹"},
    {id:"Jlvnlkk", item:"風疹"},
    {id:"Jlvnlko", item:"水痘"},
    {id:"JlvnlmI", item:"褥瘡"},
    {id:"Jlvnlpc", item:"脊髄損傷"},
    {id:"Jlvnlnk", item:"骨折"},
    {id:"Jlvnlnw", item:"骨粗鬆症"},
    {id:"Jlvnlpg", item:"脊椎椎間板ヘルニア"},
    {id:"Jlvnlpo", item:"脊柱管狭窄症"},
    {id:"Jlvnloc", item:"変形性関節症"},
    {id:"Jlvnlr8", item:"労作性狭心症"},
    {id:"JlvnlsE", item:"冠攣縮性狭心症"},
    {id:"JlvnlsI", item:"不安定狭心症"},
    {id:"JlvnlsQ", item:"急性心筋梗塞"},
    {id:"Jlvnlsc", item:"房室ブロック"},
    {id:"Jlvnlsg", item:"心房細動"},
    {id:"Jlvnlso", item:"心房粗動"},
    {id:"Jlvnlsw", item:"発作性上室頻拍症"},
    {id:"Jlvnls0", item:"心室頻拍"},
    {id:"JlvnltA", item:"心室細動"},
    {id:"JlvnltI", item:"期外収縮(上室性・心室性)"},
    {id:"Jlvnltg", item:"僧帽弁疾患(狭窄・閉鎖不全)"},
    {id:"Jlvnlts", item:"大動脈弁疾患（狭窄・閉鎖不全）"},
    {id:"JlvnluA", item:"特発性心筋症（肥大型・拡張型・拘束型）"},
    {id:"JlvnluY", item:"急性心筋炎"},
    {id:"Jlvnlug", item:"感染性心内膜炎"},
    {id:"JlvnlvY", item:"急性大動脈解離"},
    {id:"Jlvnlvc", item:"大動脈瘤（胸部・腹部）"},
    {id:"Jlvnlvk", item:"閉塞性動脈硬化症"},
    {id:"Jlvnlv0", item:"深部静脈血栓症"},
    {id:"JlvnlwI", item:"下肢静脈瘤"},
    {id:"Jlvnlwo", item:"起立性低血圧"},
    {id:"JlvnlxA", item:"急性上気道感染症（かぜ症候群）"},
    {id:"JlvnlxI", item:"扁桃炎"},
    {id:"J-RA37E", item:"気管支炎"},
    {id:"Jlvnlxc", item:"肺炎（定型・非定型）"},
    {id:"Jlvnlxg", item:"肺結核症"},
    {id:"JlvnlyE", item:"慢性閉塞性肺疾患（COPD）"},
    {id:"JlvnlyQ", item:"気管支喘息（咳喘息を含む）"},
    {id:"JlvnlzI", item:"肺血栓塞栓症"},
    {id:"Jlvnl0I", item:"睡眠時無呼吸症候群"},
    {id:"J-RA9r4", item:"急性呼吸促(窮)迫症候群<ARDS>"},
    {id:"Jlvnl1A", item:"気胸（自然・緊張性・外傷性）"},
    {id:"Jlvnl2E", item:"食道・胃静脈瘤"},
    {id:"Jlvnl2M", item:"胃食道逆流症<GERD>"},
    {id:"Jlvnl2k", item:"消化性潰瘍（胃潰瘍・十二指腸潰瘍)"},
    {id:"Jlvnl3Q", item:"機能性消化管障害（機能性ディスペプシア）"},
    {id:"Jlvnl3k", item:"急性虫垂炎"},
    {id:"Jlvnl3o", item:"腸閉塞"},
    {id:"Jlvnl30", item:"痔核・痔瘻"},
    {id:"Jlvnl4o", item:"便秘症"},
    {id:"Jlvnl34", item:"機能性消化管障害（過敏性腸症候群）"},
    {id:"Jlvnl3s", item:"潰瘍性大腸炎"},
    {id:"Jlvnl3w", item:"Crohn病"},
    {id:"Jlvnl28", item:"急性胃腸炎"},
    {id:"Jlvnl50", item:"A型肝炎"},
    {id:"Jlvnl54", item:"B型肝炎"},
    {id:"Jlvnl6A", item:"C型肝炎"},
    {id:"Jlvnl6Q", item:"急性肝炎"},
    {id:"Jlvnl6Y", item:"慢性肝炎"},
    {id:"Jlvnl6g", item:"急性肝不全"},
    {id:"Jlvnl7c", item:"脂肪肝"},
    {id:"Jlvnl64", item:"アルコール性肝障害"},
    {id:"Jlvnl6k", item:"門脈圧亢進症"},
    {id:"Jlvnl6s", item:"肝性脳症"},
    {id:"Jlvnl6w", item:"肝癌"},
    {id:"Jlvnl5M", item:"胆石症"},
    {id:"Jlvnl5U", item:"胆嚢炎"},
    {id:"Jlvnl5Y", item:"胆管炎"},
    {id:"Jlvnl7k", item:"急性膵炎（アルコール性・胆石性・特発性）"},
    {id:"Jlvnl7o", item:"慢性膵炎（アルコール性・特発性）"},
    {id:"Jlvnl70", item:"腹膜炎"},
    {id:"Jlvnl8E", item:"鼠径部ヘルニア"},
    {id:"Jlvnl8Q", item:"急性腎障害<AKI>"},
    {id:"Jlvnl8U", item:"慢性腎臓病<CKD>"},
    {id:"Jlvnl8g", item:"高・低ナトリウム血症"},
    {id:"Jlvnl8o", item:"高・低カリウム血症"},
    {id:"Jlvnl8s", item:"高・低カルシウム血症"},
    {id:"Jlvnl9M", item:"急性糸球体腎炎"},
    {id:"Jlvnl9U", item:"IgA腎症"},
    {id:"Jlvnl9Y", item:"膜性腎症"},
    {id:"Jlvnl9k", item:"微小変化群"},
    {id:"Jlvnl-M", item:"急性腎盂腎炎"},
    {id:"Jlvnl-Q", item:"糖尿病腎障害"},
    {id:"Jlvnl_I", item:"尿路結石"},
    {id:"Jlvnl_Q", item:"膀胱炎"},
    {id:"Jlvnl_U", item:"前立腺炎"},
    {id:"Jlvnl_c", item:"尿道炎"},
    {id:"Jlvnl_0", item:"前立腺肥大症"},
    {id:"JlvnmAo", item:"機能性月経困難症"},
    {id:"JlvnmA0", item:"更年期障害"},
    {id:"JlvnmBA", item:"子宮筋腫・子宮腺筋症"},
    {id:"JlvnmBE", item:"子宮内膜症"},
    {id:"JlvnmBk", item:"異所性妊娠"},
    {id:"JlvnmBs", item:"流産・切迫流産"},
    {id:"JlvnmB4", item:"妊娠高血圧症候群"},
    {id:"JlvnmCM", item:"切迫早産"},
    {id:"JlvnmCY", item:"早産"},
    {id:"JlvnmEs", item:"急性白血病"},
    {id:"JlvnmE4", item:"熱性けいれん"},
    {id:"JlvnmFA", item:"脳性麻痺"},
    {id:"JlvnmGY", item:"細気管支炎"},
    {id:"JlvnmGw", item:"腸重積症"},
    {id:"JlvnmG8", item:"乳児下痢症"},
    {id:"JlvnmHI", item:"鼠径ヘルニア"},
    {id:"JlvnmHU", item:"ネフローゼ症候群"},
    {id:"JlvnmK8", item:"甲状腺機能亢進症"},
    {id:"JlvnmLA", item:"甲状腺機能低下症"},
    {id:"JlvnmL0", item:"1型糖尿病"},
    {id:"JlvnmL8", item:"2型糖尿病"},
    {id:"JlvnmMA", item:"糖尿病ケトアシドーシス"},
    {id:"JlvnmMI", item:"高血糖高浸透圧症候群"},
    {id:"JlvnmMU", item:"糖尿病性網膜症"},
    {id:"JlvnmMY", item:"糖尿病性腎症"},
    {id:"JlvnmMg", item:"糖尿病性神経障害"},
    {id:"JlvnmMk", item:"足病変"},
    {id:"JlvnmMw", item:"脂質異常症"},
    {id:"JlvnmNE", item:"高尿酸血症・痛風"},
    {id:"JlvnmNs", item:"結膜炎・角膜炎"},
    {id:"JlvnmN4", item:"白内障"},
    {id:"JlvnmN8", item:"緑内障"},
    {id:"JlvnmOQ", item:"糖尿病・高血圧による眼底変化（糖尿病網膜症など）"},
    {id:"JlvnmO0", item:"中耳炎（急性・慢性・滲出性・真珠腫性）"},
    {id:"JlvnmPg", item:"良性発作性頭位めまい症"},
    {id:"JlvnmPo", item:"Ménière病"},
    {id:"JlvnmP0", item:"鼻出血"},
    {id:"JlvnmP4", item:"副鼻腔炎（急性・慢性）"},
    {id:"JlvnmQA", item:"アレルギー性鼻炎"},
    {id:"JlvnmQU", item:"咽頭炎"},
    {id:"JlvnmTI", item:"頸部リンパ節転移等"},
    {id:"JlvnmT0", item:"うつ病"},
    {id:"JlvnmT4", item:"双極性障害（躁うつ病）"},
    {id:"JlvnmUA", item:"統合失調症"},
    {id:"JlvnmUY", item:"身体症状症（身体化障害・疼痛性障害・心気症）"},
    {id:"JlvnmTU", item:"認知症"},
    {id:"JmxLo0Y", item:"関節リウマチ"},
    {id:"JmxLo0g", item:"全身性エリテマトーデス（SLE）及び合併症（中枢神経ループス、ループス腎炎、抗リン脂質抗体症候群）"},
    {id:"JlvnmWs", item:"IgA血管炎"},
    {id:"JlvnmW0", item:"川崎病"},
    {id:"JmxLo1A", item:"後天性免疫不全症（AIDS）"},
    {id:"JlvnmXE", item:"髄膜脳炎"},
    {id:"JlvnmXY", item:"血流感染・感染性心内膜炎"},
    {id:"JlvnmXo", item:"膀胱炎・腎盂腎炎"},
    {id:"JlvnmX4", item:"血管内留置カテーテル関連感染"},
    {id:"JlvnmX8", item:"尿路カテーテル感染"},
    {id:"JlvnmYI", item:"手術部位感染"},
    {id:"JlvnmcI", item:"肺癌"},
    {id:"Jlvnmcg", item:"食道癌"},
    {id:"Jlvnmco", item:"胃癌"},
    {id:"Jlvnmc0", item:"大腸癌"},
    {id:"JlvnmdA", item:"原発性肝癌"},
    {id:"JlvnmdQ", item:"膵癌"},
    {id:"JlvnmdY", item:"腎癌"},
    {id:"Jlvnmdg", item:"腎盂尿管癌・膀胱癌"},
    {id:"Jlvnmdk", item:"前立腺癌"},
    {id:"Jlvnmdw", item:"子宮頸癌"},
    {id:"Jlvnmd4", item:"子宮体癌（子宮内膜癌）"},
    {id:"JlvnmeA", item:"卵巣腫瘍"},
    {id:"JlvnmeQ", item:"原発性乳癌"},
  ],
  symptoms:[
    {id:"JlAK6lk",item:"発熱"},
    {id:"JlAK6lo",item:"全身倦怠感"},
    {id:"JlAK6ls",item:"食思(欲)不振"},
    {id:"JlAK6lw",item:"体重減少"},
    {id:"JlAK6l0",item:"体重増加"},
    {id:"JlAK6l4",item:"意識障害"},
    {id:"JlAK6l8",item:"失神"},
    {id:"JlAK6mA",item:"けいれん"},
    {id:"JlAK6mE",item:"めまい"},
    {id:"JlAK6mI",item:"浮腫"},
    {id:"JlAK6mM",item:"発疹"},
    {id:"JlAK6mQ",item:"咳・痰"},
    {id:"JlAK6mU",item:"血痰・喀血"},
    {id:"JlAK6mY",item:"呼吸困難"},
    {id:"JlAK6mc",item:"胸痛"},
    {id:"JlAK6mg",item:"動悸"},
    {id:"JlAK6mk",item:"嚥下困難"},
    {id:"JlAK6mo",item:"腹痛"},
    {id:"JlAK6ms",item:"悪心・嘔吐"},
    {id:"JlAK6mw",item:"吐血"},
    {id:"JlAK6m0",item:"下血"},
    {id:"JlAK6m4",item:"便秘"},
    {id:"JlAK6m8",item:"下痢"},
    {id:"JlAK6nA",item:"黄疸"},
    {id:"JlAK6nE",item:"腹部膨隆・腫瘤"},
    {id:"JlAK6nI",item:"リンパ節腫脹"},
    {id:"JlAK6nM",item:"尿量・排尿の異常"},
    {id:"JlAK6nQ",item:"血尿"},
    {id:"JlAK6nU",item:"月経異常"},
    {id:"JlAK6nY",item:"不安・抑うつ"},
    {id:"JlAK6nc",item:"認知機能障害"},
    {id:"JlAK6ng",item:"頭痛"},
    {id:"JlAK6nk",item:"運動麻痺・筋力低下"},
    {id:"JlAK6no",item:"歩行障害"},
    {id:"JlAK6ns",item:"感覚障害"},
    {id:"JlAK6nw",item:"腰背部痛"},
    {id:"JlAK6n0",item:"関節痛・関節腫脹"},
  ],
  examinations:[
    {id:"JkxirwY",item:"血算"},
    {id:"Jli6WW4",item:"生化学検査"},
    {id:"Jli6WW8",item:"凝固・線溶検査"},
    {id:"Jli6WXE",item:"免疫血清学検査"},
    {id:"Jli6WXI",item:"尿検査"},
    {id:"Jli6WXQ",item:"便検査"},
    {id:"Jkxir08",item:"血液型（ABO、RhD）検査、血液交差適合（クロスマッチ）試験、不規則抗体検査"},
    {id:"JkxirxY",item:"動脈血ガス分析"},
    {id:"Jkxiryk",item:"妊娠反応検査"},
    {id:"JkxirxU",item:"細菌学検査（細菌の塗抹、培養、同定、薬剤感受性試験）"},
    {id:"Jkxirxc",item:"脳脊髄液"},
    {id:"Jli6TOw",item:"胸水検査"},
    {id:"Jli6TO0",item:"腹水検査"},
    {id:"Jkxirwk",item:"病理組織検査や細胞診検査（術中迅速診断を含む）"},
    {id:"Jkxirwg",item:"遺伝子関連・染色体検査"},
    {id:"JkxirxQ",item:"心電図"},
    {id:"Jli6Y7U",item:"呼吸機能検査"},
    {id:"Jli6Y7Y",item:"内分泌・代謝機能検査"},
    {id:"Jli6Y7c",item:"脳波検査"},
    {id:"JkxirxA",item:"超音波検査"},
    {id:"Jkxirw4",item:"エックス線撮影"},
    {id:"Jli6aBM",item:"CT検査"},
    {id:"Jli6aBU",item:"MRI検査"},
    {id:"Jkxirxk",item:"核医学検査"},
    {id:"Jkxirw8",item:"内視鏡検査"},
  ],
  procedures:[
    {id:"JlAKx_k",item:"体位交換、移送"},
    {id:"Jub5cSY",item:"皮膚消毒"},
    {id:"Jub5cSc",item:"外用薬の貼付・塗布"},
    {id:"JlAKx_s",item:"気道内吸引"},
    {id:"Jub5dh8",item:"ネブライザー"},
    {id:"JlAKx_w",item:"静脈採血"},
    {id:"JlAKx_0",item:"末梢静脈の血管確保"},
    {id:"JlAKyAA",item:"胃管の挿入と抜去"},
    {id:"JlAKyAE",item:"尿道カテーテルの挿入と抜去"},
    {id:"JlAKyAI",item:"皮内注射"},
    {id:"JlAKyAQ",item:"皮下注射"},
    {id:"JlAKyAU",item:"筋肉注射"},
    {id:"JlAKyAY",item:"静脈内注射"},
    {id:"Jub5eUA",item:"尿検査(妊娠反応検査を含む)"},
    {id:"JlAKyAc",item:"微生物学検査（Gram 染色を含む）"},
    {id:"JlAKyAg",item:"12 誘導心電図の記録"},
    {id:"JlAKyAk",item:"臨床判断のための簡易エコー(FAST含む)"},
    {id:"JlAKyAs",item:"病原体抗原の迅速検査"},
    {id:"JlAKyAw",item:"簡易血糖測定"},
    {id:"JlAKyA0",item:"清潔操作"},
    {id:"JlAKyA4",item:"手術や手技のための手洗い"},
    {id:"JlAKyA8",item:"手術室におけるガウンテクニック"},
    {id:"JlAKyBA",item:"基本的な縫合と抜糸 "},
  ]
}